ARG CONTAINER_TAG=latest
ARG BASE_CONTAINER=onepanel/scipy-notebook:$CONTAINER_TAG
FROM $BASE_CONTAINER

LABEL maintainer="Onepanel, Inc. <support@onepanel.io>"

#Do not switch out root user, want to run as root.
USER root

RUN conda install --quiet --yes jupyterlab-git nbdime tensorboard numpy python-language-server[all] && \
    jupyter labextension install @jupyterlab/github && \
    jupyter labextension install @jupyterlab/debugger && \
    jupyter labextension install @krassowski/jupyterlab-lsp && \
    jupyter lab build -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    conda clean --all -f -y && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "/home/${NB_USER}"
